from medconsensus.orchestrator import MedConsensusOrchestrator
from medconsensus.schemas import (
    DebateRound,
    DiagnosisCandidate,
    FinalVerdict,
    FinalVerdictDiagnosis,
    RunnerUpDiagnosis,
    SpecialistOutput,
    SyntheticCaseRequest,
)


CASE = SyntheticCaseRequest(
    synthetic=True,
    patient_case="Patient: 58F synthetic case with dyspnea, orthopnea, JVD, S3, BNP 890, edema, and Kerley B lines.",
)


class FakeLLMClient:
    provider = "anthropic"

    def __init__(self) -> None:
        self.calls: list[str] = []

    def complete_json(self, system_prompt, user_payload, output_model):
        self.calls.append(output_model.__name__)
        if output_model is SpecialistOutput:
            agent = user_payload["agent"]
            return SpecialistOutput(
                agent=agent,
                diagnoses=[
                    DiagnosisCandidate(
                        name=f"{agent} LLM assessment",
                        confidence=77,
                        supporting_evidence=["Generated from role-specific LLM prompt."],
                        confirming_test="Focused confirmatory test",
                        icd10_code="R06.00",
                    ),
                    DiagnosisCandidate(
                        name=f"{agent} alternate",
                        confidence=42,
                        supporting_evidence=["Alternative generated by LLM."],
                        confirming_test="Second-line test",
                        icd10_code="R07.9",
                    ),
                ],
                challenge_to_rivals=f"{agent} generated rival challenge",
            )
        if output_model is DebateRound:
            return DebateRound(
                agent=user_payload["agent"],
                maintains_position=True,
                challenge_target="cardiology" if user_payload["agent"] != "cardiology" else "pulmonology",
                challenge_argument=f"{user_payload['agent']} generated debate critique",
                underweighted_finding="Generated underweighted finding",
            )
        if output_model is FinalVerdict:
            return FinalVerdict(
                primary_diagnosis=FinalVerdictDiagnosis(
                    name="LLM synthesized primary",
                    icd10_code="I50.9",
                    confidence=91,
                    reasoning="Generated by the mocked Consensus Agent.",
                ),
                runner_up_diagnoses=[
                    RunnerUpDiagnosis(name="LLM runner up", icd10_code="I26.99", brief_reason="Generated runner-up reasoning.")
                ],
                dissenting_view_worth_noting="Generated dissent.",
                next_steps=["Ask generated question.", "Order generated test.", "Review generated imaging."],
                red_flags=["Generated red flag."],
            )
        raise AssertionError(f"Unexpected output model: {output_model}")


def test_llm_multi_agent_calls_specialists_debate_and_consensus() -> None:
    llm = FakeLLMClient()
    report = MedConsensusOrchestrator(llm_client=llm).invoke(CASE)

    assert report.metadata["mode"] == "llm_multi_agent"
    assert llm.calls.count("SpecialistOutput") == 3
    assert llm.calls.count("DebateRound") == 3
    assert llm.calls.count("FinalVerdict") == 1
    assert report.consensus.most_likely_diagnosis == "LLM synthesized primary"
    assert report.consensus.confidence == 91


def test_deterministic_fallback_when_no_api_key(monkeypatch) -> None:
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.setenv("MEDCONSENSUS_USE_LLM", "true")

    report = MedConsensusOrchestrator().invoke(CASE)

    assert report.metadata["mode"] == "deterministic_fallback"
    assert report.consensus.most_likely_diagnosis
